### ISSUE TITLE
关于 `/opt/vlab` 下的Desktop Entry

### ISSUE THREAD

**Issue by ZhaoZuohong** [USTC-vlab/labstrap#1]
在 `/opt/vlab` 下预装了一些软件，比如 Typora 、Vivado等。但是这些软件没有关联到对应的文件格式。

以 Typora 为例，进行了一些简单的搜索与尝试：

1. Typora 的 desktop entry 在 `/opt/vlab/applications` 下，但是 `/opt/vlab` 不在 `XDG_DATA_DIRS` 环境变量中。目前该环境变量值为 `/usr/share/mate:/usr/local/share:/usr/share:/var/lib/snapd/desktop` 。对于此问题有两种解决方案：把 `/opt/vlab` 加入 `XDG_DATA_DIRS` 环境变量中，或者把 `/opt` 下的软件的 desktop entries 链接到 `/usr/share/applications` 等文件夹中。
2. 目前 Typora 的 desktop entry 中无 `MimeType` 一项，在 `typora.desktop` 中添加 `MimeType=text/markdown` 后，右键菜单中就有“使用Typora打开”的选项了。
3. 如果要设置程序的默认打开方式，可以在 `/usr/share/applications/defaults.list` 中加一行 `text/markdown=typora.desktop` 。
4. 将 Typora 与 Markdown 格式关联后，打开方式中依旧没有 Typora 选项。我认为可能是 Mate 桌面的原因。
5. 文件打开方式的设置在 `~/.config/mimeapps.list` 。

**Comment by taoky** [comment]
目前 1 和 2 都已经做了修改，不过确实打开方式里面还是没有 Typora。

如果需要的话，目前仍然需要手工介入：

1. 在 `~/.local/share/applications/`（目录如果没有则创建）创建一个指向 `/opt/vlab/applications/typora.desktop` 的软链接
2. 执行 `update-desktop-database ~/.local/share/applications/` 更新目录下的 mimeinfo db

**Comment by taoky** [comment]
一个主要的麻烦点是，构建镜像的时候是没有 /opt/vlab bind mount 的，所以即使镜像里面加了软链接，`update-desktop-database` 恐怕还是需要用户自己跑。

（这也是现在的脚本里面 touch hicolor icon cache 到 2000 年的原因，并且在每次启动的时候更新 hicolor 的 icon cache，因为如果不这么做，我们自己装的 22.04 的 native Firefox 首次启动就没有图标）

**Comment by taoky** [comment]
> 一个主要的麻烦点是，构建镜像的时候是没有 /opt/vlab bind mount 的，所以即使镜像里面加了软链接，`update-desktop-database` 恐怕还是需要用户自己跑。
> 
> （这也是现在的脚本里面 touch hicolor icon cache 到 2000 年的原因，并且在每次启动的时候更新 hicolor 的 icon cache，因为如果不这么做，我们自己装的 22.04 的 native Firefox 首次启动就没有图标）

在 /opt/vlab/applications 里面加了 mimeinfo.cache，测试了一下，现在应该是有效的。

目前只设置了 typora（我不确定 vivado 应该和什么绑定，而且我们有两个不同版本的 vivado），如果有其他的应用需要的话可以回复。
