### ISSUE TITLE
随机化定时任务时间

### ISSUE THREAD

**Issue by taoky** [USTC-vlab/labstrap#4]
已知以下的 timer 在运行时会导致对应时间段 iowait% 大幅升高：

- man-db.timer（凌晨零点）
- apt-daily-upgrade.timer（上午六点至七点）
- logrotate.timer（凌晨零点）

目前尝试关闭了 man-db.timer 和 apt-daily-upgrade.timer，但是 logrotate.timer 仍然会导致凌晨零点的时间段 iowait% 升高（尽管比 man-db.timer 情况要好一些），考虑修改配置将 `RandomizedDelaySec` 拉到整个上午。

- 修改镜像
- 如何修改现存容器？

**Comment by iBug** [comment]
镜像已添加 `/etc/systemd/system/logrotate.timer.d/vlab.conf` 设置 `RandomizedDelaySec=3h`，现存容器找个时间也做相同修改即可。
